# Generated by Django 3.0.7 on 2020-07-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
